name: Pre-commit checks

on:
  pull_request:
    types: [ opened, reopened, synchronize ]

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Run pre-commit
        uses: pre-commit/action@v3.0.0
        with:
          extra_args: --from-ref ${{ github.event.pull_request.base.sha }} --to-ref ${{ github.event.pull_request.head.sha }}
